basic/models/User.php
<?php

namespace app\models;

class User extends \yii\base\Object implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];


    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

basic/models/UserForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

class UserForm extends Model {
	public $name;
	public $email;

	public function rules() {
		return 
			[
				[['name,email'],'required'],
				['email','email'],
			];
	}

}

basic/models/Users.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

class Users extends ActiveRecord {

	public static function tableName() {
		return 'users';
	}


	public function rules() {
		return [
			[['name','password'] ,'required'],
			[['name','password'] ,'string', 'max'=>100]
		];
	}




}

basic/controllers/UsersController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Users;

class UsersController extends Controller {
	
	public function actionIndex() {
		$users = Users::find()->asArray()->all();
		//$users=json_encode($users);
		return $this->render('index',['users'=>$users]);		
	}

	public function actionCreate() {
		$model = new Users();

		// new record
		if ($model->load(Yii::$app->request->post()) && $model->save()){
			return $this->redirect(['index']);
		}

		return $this->render('create',['model'=>$model]);
	}

	public function actionEdit($id) {
		//$model = new Users();
		$model = Users::find()->where(['id'=>$id])->one();

		if ($model == null) {
			throw new NotFoundHttpException('The requested page does not exists');
		}

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			return $this->redirect(['index']);
		}

		return $this->render('edit', ['model'=>$model]);

	}

	public function actionDelete($id) {
		$model = Users::findOne($id);

		// $id not found in db
		if ($model == null) {
			throw new NotFoundHttpException('The requested page does not exists.');
		}

		$model->delete();

		return $this->redirect(['index']);
	}
}

basic/views/users/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<?php $form = ActiveForm::begin(); ?>
<?= $form->field($model, 'name'); ?>
<?= $form->field($model, 'password'); ?>
<?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']); ?>
<?php ActiveForm::end(); ?>

basic/views/users/create.php
<?=

$this->render('_form',[
	'model' => $model
])

?>

basic/views/users/edit.php
<?= $this->render('_form', [
	'model' => $model
]) ?>

basic/views/users/index.php
<?php
use yii\helpers\Html;
?>

<style>
	table th,td {
		padding: 10px;
	}
</style>

<?= Html::a('Create', ['users/create'], ['class'=>'btn btn-success']); ?>

<table border='1'>
	<tr>
		<th>Name</th>
		<th>Password</th>
		<th>Action</th>
	</tr>
	<?php foreach ($users as $k => $v) { ?>
		<tr>
			<td><?= $v['name'] ?> </td>
			<td><?= $v['password'] ?> </td>
			<td><?= Html::a('Edit', ['users/edit', 'id'=>$v['id']]) ?> | <?= Html::a('Delete', ['users/delete', 'id'=>$v['id']]) ?> </td>
		</tr>
	<?php } ?>
</table>